name: android

on:
  push:
  schedule:
  - cron: '30 1 * * *'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        context: .
        push: true
        tags: "8"

    - name: 上传工件
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ github.event.number }}
        path: '' # 根据你的打包 jar 的位置和文件名更改此路径，可以使用通配符
