name: android

on:
  push:
  schedule:
  - cron: '30 1 * * *'

permissions: read-and-write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Get repository name
      id: repo-name
      uses: MariachiBear/get-repo-name-action@v1.1.0
      with:
        with-owner: 'true'
        string-case: 'uppercase'

    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile.android
        context: .
        push: true
        tags: ${{ steps.repo-name.outputs.repository-name }}
